try:
  a = 345/10

except Exception as e:
  print(e)

# Gets executed when there is no error in the try block
else:
  print("Hey i am good")